# -*- coding: utf-8 -*-


KNOWN_PARAMETERS = [
    'OERP_ACTIVE_ID', 'OERP_ACTIVE_IDS',
    'OERP_COMPANY_NAME', 'OERP_COMPANY_LOGO', 'OERP_COMPANY_HEADER1',
    'OERP_COMPANY_FOOTER1', 'OERP_COMPANY_FOOTER2', 'OERP_COMPANY_WEBSITE',
    'OERP_COMPANY_CURRENCY', 'OERP_COMPANY_STREET', 'OERP_COMPANY_STREET2',
    'OERP_COMPANY_ZIP', 'OERP_COMPANY_CITY', 'OERP_COMPANY_COUNTRY',
    'OERP_COMPANY_PHONE', 'OERP_COMPANY_FAX', 'OERP_COMPANY_MAIL',
]

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
