# -*- coding: utf-8 -*-


{
    'name' : 'Base Openprod',
    'version' : '1.2',
    'author' : 'Objectif PI',
    'license': 'Open-prod license',
    'category' : 'Base',
    'description' : """ Base module for Open-Prod""",
    'website': 'http://objectif-pi.com',
    'images' : [],
    'depends' : [
             'decimal_precision', 
             'report',
             'web_openprod',
             'binary_attachment',
             'mail',
                ],
                
    'data': [
            'security/menu_security.xml',
            'security/ir.model.access.csv',
            'security/document_security.xml',
            'data/decimal_precision.xml',
            'data/security_groups.xml',
            'data/user_action_data.xml',
            'data/wkf_transition_group_data.xml',
            'data/default_directory.xml',
            'wizard/new_document_version_view.xml',
            'wizard/switch_document_view.xml',
            'wizard/copy_access_user_view.xml',
            'wizard/message_wizard_view.xml',
            'wizard/wizard_create_timetracking_view.xml',
            'wizard/all_reset_workflow_view.xml',
            'base_menus.xml',
            'cron_log_view.xml',
            'common_model_view.xml',
            'user_action_view.xml',
            'ir_config_parameter_view.xml',
            'workflow/workflow_view.xml',
            'company_view.xml',
            'res_currency_view.xml',
            'res_users_view.xml',
            'mrp_resource_view.xml',
            'resource_timetracking_view.xml',
            'base_openprod.xml',
            'contract_view.xml',
             ],
             
    'qweb' : [],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': True,
}