# -*- coding: utf-8 -*-
{
    'name' : 'Account Open-Prod',
    'version' : '1.4',
    'author' : 'Objectif PI',
    'category' : 'Account',
    'description' : """ Analytic distribution """,
    'license': 'LGPL',
    'website': 'http://objectif-pi.com',
    'images' : [],
    'depends' : [
             'account_voucher',
             'partner_openprod',
                ],
                
    'data': [
            'security/account_security.xml',
            'security/ir.model.access.csv',
            'data/account_openprod_data.xml',
            'data/account_cron.xml',
            'data/invoice_mail_template.xml',
            'data/workflow.xml',
            'wizard/merge_invoice_view.xml',
            'wizard/invoice_reconciliation_view.xml',
            'wizard/invoice_change_account_system_view.xml',
            'wizard/print_balance_sheet_view.xml',
            'wizard/print_balance_general_ledger_view.xml',
            'wizard/pay_more_invoice_wiz_view.xml',
            'product_view.xml',
            'res_partner_view.xml',
            'account_view.xml',
            'account_invoice_view.xml',
            'account_voucher_view.xml',
            'account_template_view.xml',
            'res_config_view.xml',
            'res_company_view.xml',
             ],
             
    'qweb' : [],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
}